### ISSUE TITLE
Could not find InAppBrowser

### ISSUE THREAD

**Issue by anonrig** [nraboy/ng-cordova-oauth#205]
Even though inAppBrowser exists in my project, I receive "Could not find InAppBrowser" error while authenticating my app with Instagram.

I'm using

```
"ng-cordova-oauth": "0.2.0",
```

I believe this function is errorous: `$cordovaOauthUtility.isInAppBrowserInstalled()`

**Comment by nraboy** [comment]
What version of the InAppBrowser plugin are you using?

**Comment by anonrig** [comment]
Hey @nraboy 
```
cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
```

**Comment by nraboy** [comment]
Fixed in the master branch.  It was in the development branch, but I forgot to merge it.

**Comment by anonrig** [comment]
Please add a new release. The problem persists. @nraboy

**Comment by nraboy** [comment]
The master does in fact work.  I tested it this morning.  Are you sure your version of the library is correct?

**Comment by anonrig** [comment]
I am using Bower to install ng-cordova-oauth. And it recognizes 0.2.2 release by default and gathers the data from there. In 0.2.2 release, this bug wasn't fixed. @nraboy

**Comment by nraboy** [comment]
https://github.com/nraboy/ng-cordova-oauth/releases/tag/0.2.3
