### ISSUE TITLE
Global var conflict

### ISSUE THREAD

**Issue by Narayon** [nraboy/ng-cordova-oauth#225]
Because the plugin adds all the oauth services it provides to the global scope, it conflicts with other services that do the same. 
An example of this is google maps, that adds the API in the global var `google`, the same global that this plugin uses for oauth with google plus. 
My work around was to add the JS file of this plugin before importing the google maps API, on my index file. It works, but I didn't test it out much and I don't know if this is the better way to do it. 
Maybe encapsulating this plugin on a different global is the better way to avoid conflicts?

**Comment by nraboy** [comment]
What version are you using?

This was corrected in a recent version @matheusrocha89 am I right?

**Comment by nraboy** [comment]
The pull request I'm referring to is this:

https://github.com/nraboy/ng-cordova-oauth/issues/189

**Comment by matheusrocha89** [comment]
Yes, this was already corrected @nraboy now all our providers have a prefix.
@Narayon I think you are using an old version of the lib, try to update and see if the error persist. This was fixed on #190 PR.

**Comment by Narayon** [comment]
I'm using the latest (0.2.3) but I still see the `window.google` global. If I don't load the OAuth script before Google API, it breaks the API import, breaking everything related to it. 
I'm using ngMap, by the way.

**Comment by nraboy** [comment]
After searching the following file:

https://raw.githubusercontent.com/nraboy/ng-cordova-oauth/master/dist/ng-cordova-oauth.js

I found no reference to window.google.  I believe you're still using an old version of the plugin.

Best,

**Comment by matheusrocha89** [comment]
@Narayon make a small search I think that ngMap is creating the window.google, take a look on their project. I saw some references to window.google on their code.

**Comment by Narayon** [comment]
It says v0.2.3 (2016-02-10) in the script header and in the bower file. 
I also can see a google global on that script (:723), like I see all the globals for all the other services on my window.
When you import the Google API, it creates the global `google`. Although ngMap may work with this global, I don't think it's responsible for creating it. 
When I import ng-cordova-oauth first, everything works. I think your plugin is replacing that global, that's the only explanation that makes sense.

**Comment by nraboy** [comment]
Do a find in your browser:

https://raw.githubusercontent.com/nraboy/ng-cordova-oauth/master/dist/ng-cordova-oauth.min.js

There is no window.google.  Show me what you see in a file on this GitHub.

**Comment by matheusrocha89** [comment]
what script in line 753 @Narayon ?

**Comment by Narayon** [comment]
Maybe I'm missing something, or doing something wrong, but I see a google global object being created on `:671` and being extended on `:723`, in ng-cordova-oauth.js. 
On my project I see the $inject prop on the google global, so I guess is from that script.
`google` is not the only global there, all the oauth services you provide are globals on my project  `window`.
Maybe encapsulating all the module on a IIFE will solve the problem.

**Comment by matheusrocha89** [comment]
Yeah, the google there is a function, maybe it's safe to use IIFE. I can
open a pull request for that. And in next version will be integrated.

Em qua, 16 de mar de 2016 12:30, Narayon <notifications@github.com>
escreveu:

**Comment by Narayon** [comment]
Thank you guys, for your time and for the plugin.

**Comment by matheusrocha89** [comment]
@Narayon I opened a PR right now, could you test the dist version of the lib on the PR to see if the error persist?

**Comment by Narayon** [comment]
I gave it a quick test, simulating the breaking behavior I had before, and it's working.
Bear in mind that the test was not very exhaustive.
Anyway, thank you for the update.

**Comment by arcreative** [comment]
The functions are all absolutely global--they're not using `window.google`, but they're declared in global scope.

In `https://raw.githubusercontent.com/nraboy/ng-cordova-oauth/master/dist/ng-cordova-oauth.js`, you have 
```
function google($q, $http, $cordovaOauthUtility) {
...
```

Means window.google is getting set.  This is a pretty big showstopper, IMO, gotta wrap these functions in parentheses to keep them from getting exposed!

**Comment by matheusrocha89** [comment]
@arcreative yes, you are correct, I already opened a pull request for that. #226

**Comment by nraboy** [comment]
Merged into dev branch. Will push to staging today for testing.  Master will be some time out

**Comment by nraboy** [comment]
Forgot to mention, these changes are in the staging branch. Please test them:

https://github.com/nraboy/ng-cordova-oauth/tree/staging

Best,
